### ISSUE TITLE
Python version alignment?

### ISSUE THREAD

**Issue by jabowery** [Xpitfire/symbolicai#3]
Install failed for me, apparently because the latest python  version (11) is incompatible with some of the `symbolicai` dependencies.  

I got it to install with:

```mamba env update --file environment.yml --prune```

where:
```
$ cat environment.yml 
name: symbolicai
dependencies:
  - python<3.11
  - pip:
    - symbolicai
```

**Comment by Xpitfire** [comment]
Thank you for addressing this. Currently, PyTorch is not fully supported with Python 3.11. See also here: https://github.com/pytorch/pytorch/issues/86566

For now, I added an environment.yml to the repository where one can use as you suggest `conda` / `mamba` to resolve the versioning.

**Comment by leoentersthevoid** [comment]
Closed. Python 3.11.x works with our framework.
