### ISSUE TITLE
working with local models like llama

### ISSUE THREAD

**Issue by Pkoiralap** [Xpitfire/symbolicai#39]
Great work on the topic. Really relevant and amazing. 

However, I couldn't find documentation regarding running it with local models like llama/vicuna.
Is that something easily achieved?

**Comment by futurisold** [comment]
@Pkoiralap the config you need to modify is this: `…/symai/backend/services/configs/huggingface_causallm.config.json`

**Comment by futurisold** [comment]
I will keep this issue open until we: 
- Have a more intuitive configuration (maybe by using `export ...` or in memory configuration objects that are loaded at init)
- Tests that that run on at least 2x backends (say CPU and accelerator) 

This would be a great contribution, if anybody wants to jump on it for the time being.
