### ISSUE TITLE
Request:  conda package with environment.yml

### ISSUE THREAD

**Issue by jabowery** [Xpitfire/symbolicai#4]
Since this library coordinates with a number of other libraries, some of which aren't  written in `python`, it would be easier for people to use `conda` (or its variant `mamba`) with an appropriate `environment.yml`.  This would minimize the need to specify version numbers since one of the strengths of `conda` is its ability to solve for version alignment across packages regardless of native programming language, including installing and updating the optimal version of `python`.

See [this related issue in stackoverflow](https://stackoverflow.com/questions/75227856/how-to-make-pip-do-as-well-as-conda-in-solving-for-python-version-during-environ).

Environment creation:
```mamba env create -f environment.yml```
Environment update:
```mamba env update --file environment.yml --prune```

**Comment by Xpitfire** [comment]
Thank you for pointing this out. I added an environment.yml to the repo.
