### ISSUE TITLE
Request: Upgrade README example of causal reasoning

### ISSUE THREAD

**Issue by jabowery** [Xpitfire/symbolicai#5]
ChatGPT nails the causal reasoning challenge currently highlighted in the README:

![image](https://user-images.githubusercontent.com/57646/214446059-696672f1-0b33-4e75-bd27-65dc307d51a3.png)

It's best to provide an example of causal reasoning that the current language models fail on since they are capable of imitating very limited depth reasoning.

**Comment by Xpitfire** [comment]
I hope the newly added extension in the causal reasoning section helps make our goals more clear.
